### ISSUE TITLE
Any plans on a swift style guide?

### ISSUE THREAD

**Issue by nickthedude** [nytimes/objective-c-style-guide#151]
Just curious.

**Comment by mattbischoff** [comment]
@nickthedude Since NYTimes folks haven’t been as responsive to issues on the repository lately, I’ll give you my 2¢ here so you’re not left hanging.

While it’s true that The Times has an internal Swift style guide that they’re using to write Swift code, it’s unclear when there will be enough organizational time, energy, or motivation to polish and release it publicly. From what I gather, there is some desire to do this inside the company, but other projects are currently taking priority.

Here are a few alternative Swift style guides that I suggest taking a look at in the mean time if you need to get started on something today:

* [The Official raywenderlich.com Swift Style Guide](https://github.com/raywenderlich/swift-style-guide)
* [LinkedIn Swift Style Guide](https://github.com/linkedin/swift-style-guide)
* [GitHub Swift Style Guide](https://github.com/github/swift-style-guide)

**Comment by nickthedude** [comment]
@mattbischoff Thanks for the response, for the sake of completeness, I think the API design guideline from Apple / Swift.org is really well thought out as well:

[Swift.org: API Design Guidelines](https://swift.org/documentation/api-design-guidelines)
